### PR TITLE
Add support to use --target and --driver in testPaths

### PR DESCRIPTION
**Pull request by viktar-d**

### CODE REVIEW

**Comment by mmcc007** [comment]
Thanks for the PR!

There are several combinations for --target and --driver that might be worth supporting (some possibly not worth it, or should be rejected). For example:
```
test_drive/main.dart # default behavior
--target=test_drive/main.dart # default behavior
--driver=test_drive/main_test.dart # runs on lib/main.dart which will not work
--target=test_drive/main.dart --driver=test_drive/main_test.dart # offers some flexibility
```
I took a stab at constructing a RegExp that parses all of the above:
https://regex101.com/r/KiT7O3/1
It looks like it is worth supporting the default option and the flexible option.

What do you think?

**Comment by viktar-d** [comment]
As suggested, I changed the implementation.
Also, I've added few tests for that validation but looks like that you have excluded that test from the run for some reason. 

Side note, personally I don't like to overcomplicate code with different regexp. Easy stupid code leaves more room for ordinary developers to contribute. Anyway, you are the supporter, fully following you guiding. 'cause it is a cool library, thanks!

**Comment by mmcc007** [comment]
Thanks for the updated implementation and tests. I recently added code coverage and disabled some test files pending some refactoring, etc... So can disregard the code coverage report.

Can you add something to the README to describe how it should be used?

**Comment by viktar-d** [comment]
yeap, no problem. Added.

**Comment by mmcc007** [comment]
Great! Thanks again!

**Pull request merged**
